server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.yuan.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://112.125.121.171:1108/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 0e107bfc0d1b4e3d

#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001

info:
  app.name: yuan-springcloud
  company.name: blog.yuan.com




